version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14  # Escolha uma imagem adequada para NodeJS
    steps:
      - checkout
      - run:
          name: Fake test
          command: echo "Fake test"
